name:                ninety-nine-problem-haskell
version:             0.1.0.0
github:              "724399396/ninety-nine-problem-haskell"
license:             BSD3
author:              "weili"
maintainer:          "liwei72439936@gmail.com"
copyright:           "2018 weili"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/724399396/ninety-nine-problem-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- QuickCheck

library:
  source-dirs: src

tests:
  ninety-nine-problem-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ninety-nine-problem-haskell
